package ui.screens

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import at.asitplus.dif.InputDescriptor
import at.asitplus.jsonpath.core.NormalizedJsonPath
import at.asitplus.misc.getRequestOptionParameters
import at.asitplus.wallet.app.common.third_parts.at.asitplus.jsonpath.core.plus
import at.asitplus.wallet.cor.CertificateOfResidenceScheme
import at.asitplus.wallet.eprescription.EPrescriptionScheme
import at.asitplus.wallet.eupid.EuPidScheme
import at.asitplus.wallet.idaustria.IdAustriaScheme
import at.asitplus.wallet.mdl.MobileDrivingLicenceScheme
import at.asitplus.wallet.por.PowerOfRepresentationScheme
import compose_wallet_app.shared.generated.resources.Res
import compose_wallet_app.shared.generated.resources.biometric_authentication_prompt_for_data_transmission_consent_subtitle
import compose_wallet_app.shared.generated.resources.biometric_authentication_prompt_for_data_transmission_consent_title
import compose_wallet_app.shared.generated.resources.error_authentication_at_sp_failed
import data.RequestOptionParameters
import data.credentials.CertificateOfResidenceCredentialAttributeTranslator
import data.credentials.EPrescriptionCredentialAttributeTranslator
import data.credentials.EuPidCredentialAttributeTranslator
import data.credentials.IdAustriaCredentialAttributeTranslator
import data.credentials.MobileDrivingLicenceCredentialAttributeTranslator
import data.credentials.PowerOfRepresentationCredentialAttributeTranslator
import io.github.aakira.napier.Napier
import kotlinx.coroutines.launch
import org.jetbrains.compose.resources.StringResource
import org.jetbrains.compose.resources.getString
import ui.views.AuthenticationConsentView

class ConsentAttributes(val scheme: String, val format: String, val attributes: List<StringResource>)