object Resources {
    const val ADD_ID_TEXT = "To add an ID, login on https://abcd.at/xyz/ with a secondary deivce and scan the displayed QR code."
    const val BUTTON_SCAN_QR = "Scan QR-Code"
    const val BUTTON_LOGIN_ID_AUSTRIA = "Login with ID Austria"
    const val CHOOSE_NEXT_STEP = "Choose next step"
    const val FIRST_NAME = "First name"
    const val LAST_NAME = "Last name"
    const val BIRTH_DATE = "Date of Birth"
    const val BUTTON_DELETE = "Delete"
    const val BUTTON_CLOSE = "Close"
    const val BUTTON_CONTINUE = "Continue"
    const val ICONS_FROM = "Icons from"
    const val PICTURES_FROM = "Pictures from"
    const val VERSION = "Version"
    const val CAMERA_ACCESS_DENIED = "Camera access denied"
    const val CREDENTIAL = "Credential"
    const val UNKNOWN = "Unknown"
    const val DEMO_WALLET = "DemoWallet"
    const val ID_AUSTRIA_CREDENTIAL = "IDAustria Credential"
    const val WALLET = "Wallet"
    const val ADD_ID = "Add ID"
    const val COMPOSE_WALLET = "Compose Wallet"
    const val DEMO_APP = "Demo App"

}