name: Build Android App
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build apk
        run: ./gradlew :androidApp:assemble
        env:
          ANDROID_CERT_PASSWORD: ${{ secrets.ANDROID_CERT_PASSWORD }}
          CI: true
      - name: Upload apk debug
        uses: actions/upload-artifact@v4
        with:
          name: Wallet App Android (debug)
          path: |
            androidApp/build/outputs/apk/debug/*.apk
      - name: Upload apk release
        uses: actions/upload-artifact@v4
        with:
          name: Wallet App Android (release)
          path: |
            androidApp/build/outputs/apk/release/*.apk
