name: Build and Test iOS

on:
  workflow_call:
    inputs:
      override-cache:
        description: "Override Cache?"
        required: false
        default: false
        type: boolean
      kotlin-version:
        description: "Override Kotlin version?"
        required: false
        default: ""
        type: string
      testballoon-version:
        description: "Override TestBalloon version (full version string)?"
        required: false
        default: ""
        type: string

jobs:
  build-and-test-ios:
    runs-on: macos-latest
    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      TESTBALLOON_VERSION_OVERRIDE: ${{ inputs.testballoon-version }}
    steps:
      - name: Common setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@feature/modularTests
        with:
          override-cache: ${{ inputs.override-cache }}

      - name: Prepare files from secrets
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            build | tee /tmp/iosApp-simulator-build.log
      - name: Upload logs (Build iOS App)
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: xcode.log
          path: "/tmp/iosApp-simulator-build.log"
      - name: Test KMP on iOS
        run: ./gradlew -U :shared:iosSimulatorArm64Test
      - name: Test Report from KMP on iOS
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Shared tests
          path: shared/build/test-results/**/TEST*.xml
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          use-actions-summary: true
