name: Build and Test Everything (All OS/Arch)

on:
  #For caching
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      kotlin-version:
        description: "Override Kotlin version?"
        required: false
        default: ""
        type: string
      testballoon-version:
        description: "Override TestBalloon version (full version string)?"
        required: false
        default: ""
        type: string

jobs:
  build-and-test-android:
    uses: ./.github/workflows/test-android.yml
    with:
      override-cache: ${{ github.ref_name == 'development' || github.ref_name == 'main' }}
      kotlin-version: ${{ inputs.kotlin-version }}
      testballoon-version: ${{ inputs.testballoon-version }}
    secrets: inherit

  build-and-test-ios:
    uses: ./.github/workflows/test-ios.yml
    with:
      override-cache: ${{ github.ref_name == 'development' || github.ref_name == 'main' }}
      kotlin-version: ${{ inputs.kotlin-version }}
      testballoon-version: ${{ inputs.testballoon-version }}
    secrets: inherit
