name: Build and Test Android

on:
  workflow_call:
    inputs:
      override-cache:
        description: "Override Cache?"
        required: false
        default: false
        type: boolean
      kotlin-version:
        description: "Override Kotlin version?"
        required: false
        default: ""
        type: string
      testballoon-version:
        description: "Override TestBalloon version (full version string)?"
        required: false
        default: ""
        type: string

jobs:
  build-and-test-android:
    runs-on: ubuntu-latest
    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      TESTBALLOON_VERSION_OVERRIDE: ${{ inputs.testballoon-version }}
    steps:
      - name: Common setup
        uses: gp-iaik/internal-workflows/.github/actions/common-setup@main
        with:
          override-cache: ${{ inputs.override-cache }}
          enable-kvm: true

      - name: Build apk
        run: ./gradlew -U :androidApp:assemble
        env:
          ANDROID_CERT_PASSWORD: ${{ secrets.ANDROID_CERT_PASSWORD }}
          CI: true

      - name: Run Android tests
        run: ./gradlew -Dkotlin.build.report.json.directory="$PWD/metrics" pixel2api35AndroidDeviceTest
        env:
          ANDROID_CERT_PASSWORD: ${{ secrets.ANDROID_CERT_PASSWORD }}
          CI: true

      - name: Reporting
        uses: gp-iaik/internal-workflows/.github/actions/common-reporting@main
        with:
          report-name: ${{ github.workflow }}
          matrix-identifier: ${{ runner.os }}-androidRunner-${{ runner.arch }}
